### ISSUE TITLE
V2 update checklist

### ISSUE THREAD

**Issue by rbcavanaugh** [rbcavanaugh/aphasia-tech-map#5]
- [x] Data sharing permission
- [x] Update website from google sheets rather than .csv
- [x] Upload google actions to re-render site every week
- [x] Add google analytics and disclaimer
- [ ] Links on CATS websites. 
- [x] Fix hyperlinks to table

@JohnEPierce please edit if I missed anything. Also - you don't need to edit anything about the google doc - its fine as is. I've updated the website to render from the link you gave me. Let me know what you think.

**Comment by JohnEPierce** [comment]
Looks good - once we have permissions I'll alter the google sheets link to the true version.

**Comment by rbcavanaugh** [comment]
Great. I managed to get the code running for the website to update itself weekly (on Mondays right now). 

Adding google analytics is trivial. You'll have to let me know what the code you'd like to use is (https://rstudio.github.io/distill/website.html#google-analytics). We can keep it private if needed.

**Comment by JohnEPierce** [comment]
I'll check who should hold the analytics - looks like CATs use ga on their site.

**Comment by rbcavanaugh** [comment]
Thanks John. I added you as a collaborator too so you should be able to go ahead and merge stuff like this. The site is set to rebuild itself automatically when a pull request is merged too - no need to do anything locally. 

I think all that's left is for M.R. to get data sharing permissions, change the google doc link, and link to cats.
